### ISSUE TITLE
Assertion error in MOI.get(model::Optimizer, ::MOI.TerminationStatus)

### ISSUE THREAD

**Issue by mlubin** [jump-dev/HiGHS.jl#46]
I've seen this assertion error trigger:

https://github.com/jump-dev/HiGHS.jl/blob/7a059816e40fcab256f13a1f6c05224f6e0b573a/src/MOI_wrapper.jl#L1587-L1590

The status in this case is `HiGHS.NOTSET`. It looks like this happens because HiGHS follows [this branch](https://github.com/ERGO-Code/HiGHS/blob/cfe064e60fdca9dc8008fd956fff04d7b562e210/src/simplex/HApp.h#L400) that never sets the model status when it fails to resolve infeasibilities due to scaling. Should this be reported as `MOI.OTHER_ERROR`? (or `MOI.NUMERICAL_ERROR` if HiGHS expands its statuses accordingly)

@jajhall

**Comment by jajhall** [comment]
Currently we leave it up to the user to decide whether, when the status of the scaled problem is optimal, the infeasibilities in the unscaled model are acceptable. In due course more will be done to resolve infeasibilities due to scaling, and the HiGHS MIP solver is providing a strong motivation to improve the simplex solver in such edge cases!

**Comment by mlubin** [comment]
> Currently we leave it up to the user to decide whether, when the status of the scaled problem is optimal, the infeasibilities in the unscaled model are acceptable.

Makes sense, although this contract with the user didn't seem to make it through to the Julia interface.
